name: Blob storage website CI

on:
   push:
      branches: [ master ]
   pull_request:
      branches: [ master ]

jobs:
  deploy_zain_haze_bot:
    name: This job will run first
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: azure login
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 