name: Blob storage website CI

on:
   push:
      branches: [ master ]
   pull_request:
      branches: [ master ]

jobs:
    deploy_zain_haze_bot:
        runs-on: ubuntu-latest
        steps:
            - name: azure login
            - uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }} 
                
