name: Blob storage website CI

on:
   push:
      branches: [ master ]
   pull_request:
      branches: [ master ]

jobs:
    deploy_zain_haze_bot:
        runs-on: ubuntu-latest
        steps:
            - name: azure login
            - uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }} 
                
            - name: azure cli script
            - uses: azure/CLI@v1
              with:
                 azcliversion: 2.0.72
                 inlineScript: |
                    az storage blob upload-batch --account-name zainhazebotstorageacc -d '$web' -s .
            
            - name: purge cdn
            - uses: azure/CLI@v1
              with:
                 azcliversion: 2.0.72
                 inlineScript: |
                    az cdn endpoint purge --content-paths  "/*" --profile-name zain-haze-bot --name zain-haze-bot --resource-group zain-haze-bot-rg
            - name: logout
            - uses: azure/CLI@v1
              with:
                 azcliversion: 2.0.72
                 inlineScript: |
                     az logout
