name: Blob storage website CD

on:
   push:
      branches: [ master ]
   pull_request:
      branches: [ master ]

jobs:
  deploy_zain_haze_bot:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
      - uses: azure/CLI@v1
        with:
            azcliversion: 2.0.72
            inlineScript: |    
              az storage blob delete-batch -s '$web' --account-name zainhazebotstorageacc
      - uses: azure/CLI@v1
        with:
            azcliversion: 2.0.72
            inlineScript: |
              az storage blob upload-batch --account-name zainhazebotstorageacc -d '$web' -s .
      - uses: azure/CLI@v1
        with:
            azcliversion: 2.0.72
            inlineScript: |
              az cdn endpoint purge --content-paths  "/*" --profile-name zain-haze-bot --name zain-haze-bot --resource-group zain-haze-bot-rg
      - uses: azure/CLI@v1
        with:
            azcliversion: 2.0.72
            inlineScript: |
                az logout
